name: Sync

on:
  push:
    branches: [main, hexo]

jobs:
  sync-2-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitlab
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITLAB
#          SSH_PRIVATE_KEY: ${{ secrets.GITLAB }}
          SSH_PRIVATE_KEY: ${{ secrets.ATOM }}
          dst_token: ${{ secrets.ATOM_TOKEN }}  # Gitcode账户的私人令牌
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:fengyanxin/fengyanxin.github.io.git
          # 注意替换为你的 Gitee 目标仓库地址
#          destination-repo: git@gitlab.com:fengyanxin/fengyanxin.git
          destination-repo: git@atomgit.com:fengyanxin/MyBlog.git
